name: test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: ${{ matrix.os }}-node-${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install handler dependencies
        working-directory: ./infra
        run: make install

      - name: Run handler tests
        working-directory: ./infra
        run: make test

      - name: Install Svelte client dependencies
        working-directory: ./web/svelte
        run: npm install

      - name: Run Svelte client tests
        working-directory: ./web/svelte
        run: npm run test
