name: test

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: ${{ matrix.os }}-node-${{ matrix.node }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [18]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}

      - name: Install login-handler dependencies
        working-directory: ./infra/login-handler
        run: npm install

      - name: Install feeds-handler dependencies
        working-directory: ./infra/feeds-handler
        run: npm install

      - name: Install entries-handler dependencies
        working-directory: ./infra/entries-handler
        run: npm install

      - name: Install last-access-handler dependencies
        working-directory: ./infra/last-access-handler
        run: npm install

      - name: Run login-handler tests
        working-directory: ./infra/login-handler
        run: npm run test

      - name: Run feeds-handler tests
        working-directory: ./infra/feeds-handler
        run: npm run test

      - name: Run entries-handler tests
        working-directory: ./infra/entries-handler
        run: npm run test

      - name: Run last-access-handler tests
        working-directory: ./infra/last-access-handler
        run: npm run test
