name: test-web

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    name: test-web
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install web client dependencies
        working-directory: ./web
        run: npm install

      - name: Run web client tests
        working-directory: ./web
        run: npm run test
