name: Unit tests

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install handler dependencies
        working-directory: ./infra
        run: make install

      - name: Run handler tests
        working-directory: ./infra
        run: make test

      - name: Install web client dependencies
        working-directory: ./web
        run: npm install

      - name: Run web client tests
        working-directory: ./web
        run: npm run test:unit
